name: Retrieve latest blog posts

on: workflow_dispatch

jobs:
  update:
    name: Update readme with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.felix-seifert.com/feed/"
